name: CI

on: 
  push:
    branches:
    - main
jobs:
  ##build:
  firebase-deploy:
    runs-on: ubuntu-latest
    ##firebase-deploy:
     
    steps:
      - uses: actions/checkout@main
      - uses: FirebaseExtended/action-hosting-deploy@main
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}