name: CI

on: 
  push:
    branches:
    - main
jobs:
  ##build:
  firebase-deploy:
    runs-on: ubuntu-latest
    ##firebase-deploy:
     
    steps:
      - uses: actions/checkout@main
      - uses: FirebaseExtended/action-hosting-deploy@main
        with:          
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_TOKEN }}"
          expires: 30d
          projectId: denticos-digest
          channelId: live