name: CI

on:
  push:
    branches: ['Version-1.0']
  pull_request:
    branches: ['Version-1.0']

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Initialize Node
        uses: actions/setup-node@v2
      - name: Install Dependencies
        run: npm install
      - name: Deploy
        uses: w9jds/firebase-action@'Version-1.0'
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
